name: Tests

on:
  push:
    branches: [main]
    paths: ["**/*.py", ".github/workflows/test.yml"]
  pull_request:
    branches: [main]
    paths: ["**/*.py", ".github/workflows/test.yml"]
  release:
    types: [published, edited]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: janosh/workflows/.github/workflows/pytest-release.yml@main
    with:
      os: ${{ matrix.os }}
      install-cmd: pip install .[test,excel]
