name: Tests

on:
  push:
    branches: [main]
    paths: ['**/*.py', '.github/workflows/test.yml']
  pull_request:
    branches: [main]
    paths: ['**/*.py', '.github/workflows/test.yml']
  release:
    types: [published]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Install dependencies
        # [test]: see options.extras_require in setup.cfg
        run: pip install .[test,excel]

      - name: Run tests
        id: tests
        run: pytest --durations 0 --cov tensorboard_reducer

      - name: Build and upload dist
        if: github.event_name == 'release' && steps.tests.outcome == 'success' && runner.os == 'Linux'
        run: |
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload --skip-existing dist/*.tar.gz
        env:
          TWINE_USERNAME: janosh
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
